apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: helioalb/hello-go:v4
        env:
          - name: NAME
            value: Helio Albano
          - name: AGE
            value: '43'
    